apiVersion: v1
kind: Service
metadata:
  name: users-crud
spec:
  type: NodePort
  selector:
    app: users-crud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
